import "@fontsource/jura";
import Head from 'next/head'
import React from 'react';
import  "next/router";
import Header from "../components/Header"
import Footer from "../components/Footer"
import LandingContent from "../components/LandingContent"
import Form from "../components/Form";
import TodoList from "../components/TodoList";
import axios from "axios";


export default function Home() {
    return (
        <div className="bg-scroll" style={{
            backgroundImage : `url('../img/main_background.jpg')`,
            backgroundRepeat : `no-repeat`,
            }}>

            <Head>
                <title>Web Dev Test</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header/>

            <LandingContent/>
            <div className="backGround">

{
            <TodoList />
}

                <div id="login">
                    <Form/>
                </div>
                <Footer/>
            </div>

        </div>
    )
}
/*
export const getServerSideProps = async () => {
    const { data } = await axios.get('http://localhost:8080/posts');
    return {
        props: {
            tasks: data.data,
        },
    };
};
*/

